### PR TITLE
Correct way for cloning projects

### PR DESCRIPTION
**Pull request by cordoval**

### CODE REVIEW

**Comment by andyfleming** [comment]
When making changes, you should make changes to the `.md` files while running `npm run dev` which will watch for changes and compile to html automatically.

**Comment by andyfleming** [comment]
For cloning the project, I would actually recommend the following flow:

1. Fork `mc-core` on github

2. Clone your fork locally

  ```
  git clone git@github.com:your-github-username/mc-core.git
  ```
3. Add the upstream repo

  ```
  git remote add upstream git@github.com:space-race/mc-core.git
  ```

**Comment by cordoval** [comment]
ok on it

**Comment by cordoval** [comment]
I see, we disagree on this best practice. I will just close this PR since it is not critical to the project. But will focus on the other aspects.

**Comment by andyfleming** [comment]
Fair enough. I was following GitHub's recommendations here: [GitHub Help » Fork A Repo ](https://help.github.com/articles/fork-a-repo/)

**Comment by cordoval** [comment]
That works well until you have more than 2 people working together. Then usernames are the deal.

**Comment by andyfleming** [comment]
Gotcha. I typically set up my remotes like this:

```
origin	    git@github.com:andyfleming/mc-core.git (push)
origin	    git@github.com:andyfleming/mc-core.git (fetch)
cordoval	git@github.com:cordoval/mc-core.git (push)
cordoval	git@github.com:cordoval/mc-core.git (fetch)
upstream	git@github.com:space-race/mc-core.git (fetch)
upstream	git@github.com:space-race/mc-core.git (push)
```

**Comment by cordoval** [comment]
I know, it is a bit confusing since andyfleming is not the origin. There is only one origin which is upstream.

**Pull request closed without merging**
